[workspace]
members = [
    ".",
    "sqlx-core",
    "sqlx-macros",
    "examples/realworld-postgres"
]

[package]
name = "tokio-sqlx"
version = "0.1.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/vorot93/tokio-sqlx"
documentation = "https://docs.rs/tokio-sqlx"
description = "🧰 The Rust SQL Toolkit."
edition = "2018"
keywords = [ "database", "sql", "async", "await" ]
categories = [ "database", "asynchronous" ]
authors = [
    "Ryan Leckey <leckey.ryan@gmail.com>", # ryan@launchbadge.com
    "Austin Bonander <austin.bonander@gmail.com>", # austin@launchbadge.com
    "Zachery Gyurkovitz <zgyurkovitz@gmail.com>", # zach@launchbadge.com
    "Daniel Akhterov <akhterovd@gmail.com>", # daniel@launchbadge.com
    "Artem Vorotnikov <artem@vorotnikov.me>"
]

[features]
default = [ "macros" ]
macros = [ "sqlx-macros", "proc-macro-hack" ]

# database
postgres = [ "sqlx-core/postgres", "sqlx-macros/postgres" ]
mysql = [ "sqlx-core/mysql", "sqlx-macros/mysql" ]

# types
chrono = [ "sqlx-core/chrono", "sqlx-macros/chrono" ]
uuid = [ "sqlx-core/uuid", "sqlx-macros/uuid" ]

[dependencies]
futures-intrusive = "*"
sqlx-core = { package = "tokio-sqlx-core", version = "=0.1.0", path = "sqlx-core" }
sqlx-macros = { package = "tokio-sqlx-macros", version = "0.1.0", path = "sqlx-macros", optional = true }
proc-macro-hack = { version = "0.5.11", optional = true }

[dev-dependencies]
anyhow = "1.0.26"
futures = "0.3.1"
dotenv = "0.15.0"
tokio = { version = "0.2.8", features = ["full"] }

[package.metadata.docs.rs]
all-features = true

[[test]]
name = "postgres-macros"
required-features = [ "postgres", "macros" ]

[[test]]
name = "mysql"
required-features = [ "mysql" ]

[[test]]
name = "postgres"
required-features = [ "postgres" ]

[[test]]
name = "postgres-types"
required-features = [ "postgres" ]

[[test]]
name = "postgres-types-chrono"
required-features = [ "postgres", "chrono" ]

[[test]]
name = "mysql-types"
required-features = [ "mysql" ]

[[test]]
name = "mysql-types-chrono"
required-features = [ "mysql", "chrono" ]
