[package]
name = "tokio-sqlx-core"
version = "0.1.0"
repository = "https://github.com/vorot93/tokio-sqlx"
description = "Core of SQLx, the rust SQL toolkit. Not intended to be used directly."
license = "MIT OR Apache-2.0"
edition = "2018"
authors = [
    "Ryan Leckey <leckey.ryan@gmail.com>", # ryan@launchbadge.com
    "Austin Bonander <austin.bonander@gmail.com>", # austin@launchbadge.com
    "Zachery Gyurkovitz <zgyurkovitz@gmail.com>", # zach@launchbadge.com
    "Daniel Akhterov <akhterovd@gmail.com>", # daniel@launchbadge.com
    "Artem Vorotnikov <artem@vorotnikov.me>"
]

[features]
default = []
unstable = []
postgres = [ "md-5" ]
mysql = [ "sha-1", "sha2", "generic-array", "num-bigint", "base64", "digest", "rand" ]

[dependencies]
async-stream = { version = "0.2.0", default-features = false }
base64 = { version = "0.11.0", default-features = false, optional = true, features = [ "std" ] }
bitflags = { version = "1.2.1", default-features = false }
byteorder = { version = "1.3.2", default-features = false }
chrono = { version = "0.4.10", default-features = false, features = [ "clock" ], optional = true }
digest = { version = "0.8.1", default-features = false, optional = true, features = [ "std" ] }
futures-core = { version = "0.3.1", default-features = false }
futures-intrusive = "0.2"
futures-util = { version = "0.3.1", default-features = false }
generic-array = { version = "0.12.3", default-features = false, optional = true }
log = { version = "0.4.8", default-features = false }
md-5 = { version = "0.8.0", default-features = false, optional = true }
memchr = { version = "2.2.1", default-features = false }
num-bigint = { version = "0.2.3", default-features = false, optional = true, features = [ "std" ] }
rand = { version = "0.7.2", default-features = false, optional = true, features = [ "std" ] }
sha-1 = { version = "0.8.1", default-features = false, optional = true }
sha2 = { version = "0.8.0", default-features = false, optional = true }
tokio = { version = "0.2.8", features = [ "full" ] }
url = { version = "2.1.0", default-features = false }
uuid = { version = "0.8.1", default-features = false, optional = true }

[dev-dependencies]
matches = "0.1.8"

[package.metadata.docs.rs]
all-features = true
